In [ ]:
print("Hello World")

Hello World


In [ ]:
import numpy
# import numpy as np
# from numpy import arange
# from numpy import *
# n = numpy.arange(11)
# print(type(n))
# print(n)
# print(n[0])


# example
# n = numpy.arange(12)
# d = n.reshape(3,4) # 3 -> rows or 4 -> cols
# print(type(d))
# print(d)

#example 2d
# n = numpy.arange(12).reshape(4,3)
# print(n)


# example 3d
# n = numpy.arange(24).reshape(1,6,4) # 3-> rows or 4 -> cols
# print(n)


# example split # 2,5,8,11 -> print
# n = numpy.arange(12).reshape(4,3)
# print(n)
# print(n[0:4:,2]) # first row or second cols
# print(n[0:4,2:4]) # first row or second cols
# print(n[:,-1])

#example split # 4,7 -> print
n = numpy.arange(12).reshape(4,3)
print(n)
print(n[1:3,1:2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4]
 [7]]


In [4]:
import numpy as np
# list 1d
l = [1,2,3]
print(l)

# array 1d
arr = np.array(l)
print(arr)

# 2d example

import numpy as np
# 2d list
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0]) # [1,2,3] -> 1row
print(l[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question list value 4 -> 100
l[1][0] = 100
print(l[1])

# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0]) # [1,2,3] -> 1 row
print(arr[0][0]) # [1,2,3] -> 1row -> first element -> 1

# question array value 4 -> 100
arr[1][0] = 100
print(arr[1])

[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
[100, 5, 6]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[100   5   6]
